name: upper
description: Back-end framework for Dart. Make a automated GRPC API For Relational Databases.
version: 0.0.2-dev
homepage: https://github.com/andriwsluna/upper/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  postgres: ^2.3.2
  file_utils: ^1.0.0
  data_db: ^0.0.2
  static_orm_generator: ^0.0.3-dev
  static_postgres_orm: ^0.0.5-dev
  static_grpc: ^0.0.2-dev
  static_grpc_generator: ^0.0.1-dev
  
  dartz: ^0.10.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
